- config/views.py
- docker/extensions/README.md
- ej/templates/jinja2/pages/rocket-intro.jinja2
- lib/assets/css/main.css
- lib/assets/css/rocket.css
- lib/scss/4_elements/_buttons.scss
- lib/scss/6_components/_index.scss
- lib/scss/6_components/_rocket-intro.scss
- lib/scss/rocket.scss
- tasks.py
> Rocket intro

- ej/templates/jinja2/base.jinja2
- ej/templates/jinja2/components/generic/page_top_header.jinja2
- lib/assets/css/main.css
- lib/scss/1_settings/_layout.scss
- lib/scss/6_components/generic/_index.scss
- lib/scss/6_components/generic/_page-header.scss
- lib/scss/6_components/generic/_page-top-header.scss
- lib/scss/6_components/generic/_page.scss
adds page_top_header (Only for desktop version) with static links to about, faq, and usage.
> Page top header

- src/ej_conversations/models/conversation.py
> Approving conversation author comment when created

- configure.sh
- etc/requirements/develop.txt
- etc/scripts/chromedriver.sh
- src/ej/fixes/unregister_admin.py
- src/ej/settings/apps.py
- src/ej_conversations/mixins.py
- src/ej_conversations/rules.py
- src/ej_conversations/tests/test_ui.py
- tasks.py
#287 
-  Usuário entra em uma conversa, tenta votar em um comentário, vê a mensagem para logar, clica nela, faz o login e volta pra votar novamente na conversa 
Com esse teste criou-se a issue #381
> Start front-end tests

- lib/assets/js/utils.js
Corrige o comportamento do navbar em todas as páginas. Agora, em todas as páginas, o navbar é exibido quando a barra de rolagem está no top. Ao rolar a tela, o navbar é ocultado.
resolves: #393
> Fix navbar behavior on scroll

- src/ej_conversations/jinja2/ej_conversations/detail.jinja2
Reverts ejplatform/ej-server#430
> Revert "WIP: I421 Update text on no comments left"

- lib/assets/js/utils.js
Conserta o comportamento da bottom nav
#443
> fixes bottom nav

- lib/scss/6_components/_home-commercial.scss
Corrige um bug visual no carousel da home, onde o mesmo se encontrava muito abaixo da página, chegando a sumir em algumas resoluções.
#442
> fixes home carousel

- lib/scss/6_components/generic/_page-header.scss
- src/ej_conversations/jinja2/ej/role/comment-card.jinja2
Este pull está relacionado aos ajustes na nav-bar
resolves: #406
> Adjust icon size

- lib/scss/1_settings/_options.scss
Ajuste na color da nomeclatura do icone na navbar, onde consegui mudar para a cor que estava no invision, ou seja, deixando o mais parecido com o protótipo. 
resolves: #468
> [REVIEW] Adjust color nomenclature navbar

- etc/requirements/local.txt
Atualização da versão do django taggit para correção de bug relacionado a versão 2.1. do django (função render teve mudança na sua assinatura)
resolves #466
> [REVIEW] Consertando bug de criação de conversa no board de usuário

- src/ej_boards/routes.py
- src/ej_boards/tests/test_routes.py
- src/ej_conversations/jinja2/ej_conversations/moderate.jinja2
- src/ej_conversations/routes/admin.py
Dificuldades nas rotas de acesso para moderação e edição de conversas em boards, bem como falta de definição da necessidade de ser dono do board para editar as conversas. Foram também adicionados testes 
resolves #493
> [REVIEW] Fixing board routes bugs

- src/ej_conversations/jinja2/ej/role/comment-form.jinja2
Utilizando o unpoly para realizar a requisição a página não é recarregada e, portanto, não retorna ao início.
resolves #394
> [REVIEW] Prevents page reloading on comment form submit

- lib/scss/6_components/_profile.scss
- src/ej_profiles/jinja2/ej_profiles/detail.jinja2
Adiciona seta para indicar a aba atual.
resolves #472
> [REVIEW] Add arrow to profile tabs

- lib/assets/js/web-share.js
Utiliza a api de compartilhamento, se disponível, caso contrário copia para a área de transferência.
resolves #457
> [REVIEW] Enable share button on conversations

- src/ej/templates/jinja2/components/generic/page_header.jinja2
Tirei o botão de voltar da página de conversas e da home, onde o mesmo não fazia sentido
resolves: #469
> [WIP] Remove back bottom

- lib/scss/1_settings/_options.scss
- lib/scss/6_components/_conversations.scss
- lib/themes/cpa/scss/_overrides.scss
- src/ej_boards/routes.py
- src/ej_conversations/jinja2/ej_conversations/list.jinja2
- src/ej_conversations/routes/conversations.py
Adiciona botão de editar board
#449 
CPA:
(Há umas pequenas diferenças do Invision, mas com certeza elas cabem para outra issue)
Genérico:
> [WIP] creates button to edit board on board page

- src/ej_boards/routes/__init__.py
- src/ej_clusters/routes.py
Corrigindo o lookup field de boards nas rotas de boards, corrigindo assim o problema na rota de edição de esteriótipo em uma conversa
#534
> [REVIEW] i534 Fixing edit stereotype of a board conversation route

- src/ej/templates/jinja2/components/generic/page_menu.jinja2
Adiciona um link ao menu hambúrguer que leva à documentação.
Nenhuma.
> [REVIEW] Add link to documentation

- src/ej_conversations/models/comment.py
- src/ej_conversations/models/utils.py
- src/ej_conversations/tests/test_models.py
- src/ej_conversations/tests/test_views.py
- src/ej_profiles/routes.py
Alterando a implementação dos métodos de contagem de votos de um comentário
resolves #572
> [REVIEW] I572 Changing comment votes count implementation

- src/ej_conversations/jinja2/ej_conversations/detail.jinja2
- src/ej_conversations/routes/conversations.py
- src/ej_conversations/rules.py
Adiciona uma nova regra para calcular o número de comentários sob moderação.
resolves #421
> [REVIEW] Update no comments left text

- lib/scss/6_components/_conversations.scss
Mudança da cor do fundo do formulário de comentários.
#604
> [REVIEW] Color form conversation

- src/ej_conversations/models/conversation.py
Na contagem, estavam sendo contabilizados votos para comentários que antes estavam aprovados e depois foram rejeitados
resolves: #620
> [REVIEW] Bug de contagem de votos contabilizando comentários que foram rejeitados

- lib/scss/6_components/_conversations.scss
- lib/scss/6_components/generic/_page-header.scss
- lib/scss/6_components/generic/_page.scss
- src/ej/templates/jinja2/base.jinja2
Implementa um novo layout para desktop em que a barra lateral é fixa e há mais de uma conversa por linha na tela de conversas.
resolves: #557 
Vídeo: https://www.youtube.com/watch?v=KRwHRRSmVEc
> [REVIEW] Layout desktop

- etc/requirements/local.txt
[REVIEW] Upgrade DjangoAllAuth
> Minor Release 1.3.1 - Ada Lovelace

- src/ej/templates/jinja2/base.jinja2
- src/ej_boards/jinja2/ej_boards/conversation-list.jinja2
- src/ej_conversations/jinja2/ej_conversations/detail.jinja2
Alteração dos metadados para as páginas de board e conversation ao serem compartilhadas
Resolves: #626
> [Review] I626 Share conversation and boards text 

- src/ej/templates/jinja2/base.jinja2
- src/ej_boards/jinja2/ej_boards/conversation-list.jinja2
- src/ej_conversations/jinja2/ej_conversations/detail.jinja2
Add specific text for board's and conversation's link shared on social media.
> Minor release 1.3.2 - Ada Lovelace

- .gitignore
- Pipfile
- etc/requirements/local.txt
- src/ej/testing/url_tester.py
- src/ej_notifications/models.py
- src/ej_profiles/choices.py
- src/ej_reports/rules.py
- src/ej_users/routes.py
> [REVIEW] Update boogie version to 0.11.0

- src/ej_clusters/models.py
- src/ej_conversations/managers.py
- src/ej_conversations/models/conversation.py
- src/ej_conversations/models/vote.py
- src/ej_conversations/roles.py
- src/ej_conversations/routes/admin.py
- src/ej_conversations/routes/conversations.py
Otimiza queries e implementa algumas lógicas de agregação utilizando dataframes nos querysets do ej_conversations. Utiliza funcionalidades da nova versão do boogie (in progress)
> [REVIEW] Otimiza queries no app ej_conversations

- src/ej_users/socialbuttons.py
Redireciona o usuário de volta para a página em que ele estava, ao realizar o login utilizando uma rede social.
resolves: #672 
Ver vídeo em https://www.youtube.com/watch?v=cLxAy54yCpk.
> [REVIEW] Redirect to previous page when logging in with social account

- src/ej_conversations/forms.py
- src/ej_conversations/jinja2/ej/role/conversation-card.jinja2
- src/ej_conversations/jinja2/ej_conversations/create.jinja2
- src/ej_conversations/jinja2/ej_conversations/edit.jinja2
- src/ej_conversations/jinja2/ej_conversations/moderate.jinja2
- src/ej_conversations/roles.py
- src/ej_conversations/routes/admin.py
- src/ej_conversations/tests/test_forms.py
- src/ej_users/socialbuttons.py
This include PRs: #673 and #664 
Fixing redirects from social login and some conversation tags rules.
> Minor Release 1.3.3 Ada Lovelace

- lib/scss/6_components/_conversations.scss
Estilos fora do padrão na tela de criação de nova conversa
resolves: #680 
Antes:
Depois:
> [REVIEW] Template criação de nova conversa
